name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-passing-data:
    uses: shahul75/shared-nodejs/.github/workflows/node.js.yml@main
    with:
      no_inputs: no_values
    secrets: inherit

 
